<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hostedvoicefp</name>
   <tag></tag>
   <elementGuidId>39f0b67b-d78f-4508-8010-47b487cf5fa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div/div[2]/form/div[1]/ul/li[40]/a[2][count(. | //*[@ref_element = 'Object Repository/hostedvoicefp/hostedvoicefp/Page_My Tele2 Business - Account Details/iframe_pYour browser does not support iframe elementsp']) = count(//*[@ref_element = 'Object Repository/hostedvoicefp/hostedvoicefp/Page_My Tele2 Business - Account Details/iframe_pYour browser does not support iframe elementsp'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='functionGroupsTree']/ul/li[41]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox checked</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div/div[2]/form/div[1]/ul/li[40]/a[2]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/hostedvoicefp/hostedvoicefp/Page_My Tele2 Business - Account Details/iframe_pYour browser does not support iframe elementsp</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='functionGroupsTree']/ul/li[41]/a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[41]/a[2]</value>
   </webElementXpaths>
</WebElementEntity>
