<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframeNL</name>
   <tag></tag>
   <elementGuidId>4fa432b8-b73c-4c0b-a9f3-3c3d838b0450</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//radio-group[@id='myProfileLanguage']/div/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//radio-group[@id='myProfileLanguage']/div/span/i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/iframe/Page_Mijn Profiel/iframe_Geen notificaties beschikbaar_id_1_1</value>
   </webElementProperties>
</WebElementEntity>
