<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NLredtickenabled</name>
   <tag></tag>
   <elementGuidId>110e4bfa-e56a-47a9-9129-d0e539b4b050</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//radio-group[@id='myProfileLanguage']/div/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa radio-field-icon radio-field-border-left fa-times text-red</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;container-fluid&quot;]/div[1]/div[@class=&quot;bp-section&quot;]/div[@class=&quot;bp-section-body&quot;]/div[@class=&quot;bp-section-body-container&quot;]/div[@class=&quot;section-row&quot;]/div[@class=&quot;section-row-segment section-row-segment-2x&quot;]/radio-group[@id=&quot;myProfileLanguage&quot;]/div[@class=&quot;input-field radio-field-group&quot;]/span[@class=&quot;radio-field&quot;]/i[@class=&quot;fa radio-field-icon radio-field-border-left fa-times text-red&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/iframe_No messages available_id_1_1</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//radio-group[@id='myProfileLanguage']/div/span/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/radio-group/div/span/i</value>
   </webElementXpaths>
</WebElementEntity>
