<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mcfpunchecked</name>
   <tag></tag>
   <elementGuidId>90178891-b7c3-47e0-be11-535aa9329648</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div/div[2]/form/div[1]/ul/li[51]/a[2][count(. | //*[@ref_element = 'Object Repository/mobileconnectfp/mcunchecked/Page_My Tele2 Business - Account Details/iframe_pYour browser does not support iframe elementsp']) = count(//*[@ref_element = 'Object Repository/mobileconnectfp/mcunchecked/Page_My Tele2 Business - Account Details/iframe_pYour browser does not support iframe elementsp'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='functionGroupsTree']/ul/li[51]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox unchecked</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div/div[2]/form/div[1]/ul/li[51]/a[2]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/mobileconnectfp/mcunchecked/Page_My Tele2 Business - Account Details/iframe_pYour browser does not support iframe elementsp</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='functionGroupsTree']/ul/li[51]/a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[51]/a[2]</value>
   </webElementXpaths>
</WebElementEntity>
