<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>statusfilter</name>
   <tag></tag>
   <elementGuidId>df038aec-dbc3-440e-ad14-a8159b00e2e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='orders-reacttable']/div/span[5]/div/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#orders-reacttable > div.filterPannel > span.filter-field.select-box-status > div.selectbox > div.selectbox-selection > i.fa.fa-chevron-down.arrow-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-chevron-down arrow-down</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;orders-reacttable&quot;)/div[@class=&quot;filterPannel&quot;]/span[@class=&quot;filter-field select-box-status&quot;]/div[@class=&quot;selectbox&quot;]/div[@class=&quot;selectbox-selection&quot;]/i[@class=&quot;fa fa-chevron-down arrow-down&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Welcome to Business Portal/i_Status_fa fa-chevron-down arrow-down (1)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='orders-reacttable']/div/span[5]/div/div/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/span[5]/div/div/i</value>
   </webElementXpaths>
</WebElementEntity>
